
module.exports = {
    colors: {
        col1: '#FF0033',
        text1: 'red',
        text2: 'grey',
        text3: 'black',
    },
    titles: {
        title1: 30,
        btntxt: 20,
    },
    btn1: {
        width: '80%',
        height: 50,
        backgroundColor: 'red',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        color: 'white',
    },
    btn2: {
        width: 150,
        height: 50,
        backgroundColor: 'green',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        color: 'white',
        margin: 10,
    },
    btnlogin: {
        width: '80%',
        height: 50,
        backgroundColor: '#27AE60',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        color: 'white',
    },
    hr80: {
        width: '80%',
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        marginVertical: 20,
    },
    veg: {
        backgroundColor: 'green',
        width: 50,
        height: 50,
        borderRadius: 5,
    },
    nonveg: {
        backgroundColor: 'red',
        width: 20,
        height: 20,
        borderRadius: 5,
    },
    navbtn: {
        backgroundColor: 'black',
        width: 50,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        borderRadius: 50,
        borderTopLeftRadius: 0,
    },
    navbtnin: {
        color: 'white'
    },
    navbtnout: {
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
    },
    incdecbtn: {
        backgroundColor: 'green',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        elevation: 10,
        padding: 10,
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',
    },
    incdecinput:{
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        padding: 10,
        width: 50,
        marginHorizontal: 10,
        fontSize: 20,
    },
    incdecout:{
        flexDirection: 'row',
        alignItems: 'center',
        margin: 10,
    },
   
}